### ISSUE TITLE
Upgrade to latest Versions

### ISSUE THREAD

**Issue by scpeterson** [jarroda/FluentMigrator.ServiceStack#10]
I am using the latest FluentMigrator.ServiceStack4, in a project that uses ServiceStack 4.0.36.0.  That doesn't seem to have caused any problems, but I am trying to run the dashboard against migrations build using FluentMigrator 1.4 while the dashboard uses FluentMigrator 1.1.1.  When I compile I get:

Error	2	Assembly 'Data.Migrations.Company, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'FluentMigrator, Version=1.4.0.0, Culture=neutral, PublicKeyToken=aacfc7de5acabf05' which has a higher version than referenced assembly 'FluentMigrator, Version=1.1.1.0, Culture=neutral, PublicKeyToken=aacfc7de5acabf05'	c:\Dev\serverbase\ServerBase\Data.Migrations.Company\bin\Debug\Data.Migrations.Company.dll	Web

Is solving this as simple as upgrading the dashboard to the latest FluentMigrator?

**Comment by jarroda** [comment]
I would probably be possible to use a [binding redirect](https://msdn.microsoft.com/en-us/library/433ysdt1%28v=vs.80%29.aspx), but I just merged in a pull request adding FluentMigrator 1.4.  I will push this out to nuget ASAP.

**Comment by jarroda** [comment]
Nuget package update released. Let me know if you have any issues.

**Comment by scpeterson** [comment]
It compiles just fine now, thanks!  If there are other issues, I'll submit them separately.
